### ISSUE TITLE
Remove tcp

### ISSUE THREAD

**Issue by mb-14** [kartikeya1994/isw#1]
TCP is shit.

**Comment by litesaber15** [comment]
Dear Miroojin,
What are you going to do if by chance a UDP packet drops? TCP send and receive functions are ready, just use them -.- Check MachineList class.

**Comment by mb-14** [comment]
Socket refuses to connect if ServerSocket is not accepting connections. Which means we have to maintain a separate accepting socket for each incoming piece of data. :-1:
